---
stages:
  - lint
  - build doc
  - publish doc
  - test

lint:
  script: merchise_lint2
  stage: lint
  tags:
    - merchise-lint

.run_tests: &run_tests
  stage: test
  tags:
    - virtualenv
    - xoeuf-tester
  script:
    - export CWD=`pwd`
    - cd ~/src/$ODOO_WORKTREE
    - git pull
    - mkdir -p ~/virtualenvs
    - rm -rf ~/virtualenvs/$CI_PROJECT_NAME-$ODOO_WORKTREE || true
    - virtualenv -p `which $PYTHON` ~/virtualenvs/$CI_PROJECT_NAME-$ODOO_WORKTREE
    - source ~/virtualenvs/$CI_PROJECT_NAME-$ODOO_WORKTREE/bin/activate
    - pip install -r requirements.txt
    - pip install -U "six>=1.9.0" "decorator>=4.0,<4.2" "hypothesis>=3.24"
    - pip install -e .
    - cd $CWD
    - pip install -r requirements.txt
    - pip install -e .
    - export ADDONS=`find xopgi/ -maxdepth 2 -mindepth 2 -type d -name 'tests' | xargs dirname | while read f; do basename $f; done | xargs | tr " " ","`
    - cd ~/src/$ODOO_WORKTREE
    - runtests-odoo.sh -i $ADDONS

run all Odoo 10 tests:
  <<: *run_tests
  variables:
    PYTHON: python
    ODOO_WORKTREE: odoo10
  only:
    - branches


build documentation:
  stage: build doc
  script:
    - mkdir -p envs
    - virtualenv envs/$CI_COMMIT_SHA
    - source envs/$CI_COMMIT_SHA/bin/activate
    - pip install sphinx sphinx-rtd-theme
    - make -C docs/ html
    - cd docs/build/html
    - tar -cjf ../../../$CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 ./
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    expire_in: 4 days
  tags:
    - virtualenv

publish in our rtd:
  variables:
    GIT_STRATEGY: none
  stage: publish doc
  script:
    - scp $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 rtd@docs.lahavane.com:.
    - ssh rtd@docs.lahavane.com mkdir -p $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com tar -xf $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 -C $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com "rm -r /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME; ln -sr /var/www/html/$CI_PROJECT_NAME/.$CI_COMMIT_SHA /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - ssh rtd@docs.lahavane.com rm $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    - ssh rtd@docs.lahavane.com "cd /var/www/html/$CI_PROJECT_NAME; ls -al | grep -oE '\.([0-9]|[a-z])*$' | sort | uniq -c | grep '1 ' | grep -oE '\.([0-9]|[a-z])*$' | xargs rm -rf"
  tags:
    - rtd@docs.lahavane.com
  dependencies:
    - build documentation
  environment:
    name: docs.lahavane.com
    url: http://docs.lahavane.com/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
